### ISSUE TITLE
Provide usage examples

### ISSUE THREAD

**Issue by abshinn** [kwhanalytics/rdtools#10] opened 2017-03-02 16:40 UTC
- Standardize degradation function outputs and printed output.
- Commit notebooks with usage examples of the code.
- Supply links to notebooks ([notebooks would be rendered so that users do not need to launch Jupyter Notebook to view the code and plots](http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/)).

**Comment by mdeceglie** [comment] 2017-04-13 21:54
This appears to be a duplicate of #13. I will close this and open a new issue on standardizing degradation function outputs.

**Closed by mdeceglie** 2017-04-13 21:54 UTC
